version: '3'

services:
  pixelflut:
    build: pixelflut/
    ports:
      - "1337:1337"
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600
    depends_on:
      - stream
    networks:
      frontend:
        ipv4_address: 10.0.1.1

  stream:
    build: stream/
    ports:
      - "8000:80"
      - "1935:1935"
    networks:
      frontend:
        ipv4_address: 10.0.2.1

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.1/16

