version: '3'

services:
  traefik:
    image: caddy:2
    restart: unless-stopped
    environment:
      - "DOMAIN=${DOMAIN:-localhost}"
    networks:
      frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"

  pixelflut:
    build: pixelflut/
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600
    depends_on:
      - stream
    ports:
      - "1337:1337"
    networks:
      frontend:
        ipv4_address: 10.0.1.1

  stream:
    build: stream/
    networks:
      frontend:
        ipv4_address: 10.0.2.1

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.1/16

volumes:
  caddy_data:
  caddy_config:

