version: '3'

services:
  traefik:
    image: traefik:v2.4
    restart: always
    environment:
      - "DOMAIN=${DOMAIN}"

      # - "TRAEFIK_API_INSECURE=true"
      # - "TRAEFIK_API=true"
      # - "TRAEFIK_API_DASHBOARD=true"

      - "TRAEFIK_PROVIDERS_DOCKER=true"
      - "TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=true"
      - "TRAEFIK_PROVIDERS_FILE_DIRECTORY=/traefik/config"

      - "TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80"
      - "TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443"
      - "TRAEFIK_ENTRYPOINTS_PIXELFLUT_ADDRESS=:1337"
    networks:
      frontend:
    ports:
      # - "8080:8080"
      - "80:80"
      - "443:443"
      - "1337:1337"
    volumes:
      - "./traefik/${SETUP:-production}:/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock"

  pixelflut:
    build: pixelflut/
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600
    depends_on:
      - stream
    networks:
      frontend:
        ipv4_address: 10.0.1.1
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.pixelflut-tcp.entrypoints=pixelflut"
      - "traefik.tcp.routers.pixelflut-tcp.rule=HostSNI(`*`)"
      # - "traefik.tcp.routers.stream-tcp.rule=HostSNI(`${DOMAIN}`)"

  stream:
    build: stream/
    networks:
      frontend:
        ipv4_address: 10.0.2.1
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.stream-http.entrypoints=web"
      - "traefik.http.routers.stream-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.stream-http.middlewares=redirect-to-https@file"

      - "traefik.http.routers.stream-https.entrypoints=websecure"
      - "traefik.http.routers.stream-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.stream-https.tls=true"

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.1/16

