version: '3'

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    environment:
      DOMAIN: "${DOMAIN:-localhost}"
    networks:
      frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"

  site:
    build: site
    restart: unless-stopped
    networks:
      frontend:

  pixelflut:
    restart: unless-stopped
    build: pixelflut/
    environment:
      SCREEN_WIDTH: ${SCREEN_WIDTH:-800}
      SCREEN_HEIGHT: ${SCREEN_HEIGHT:-600}
      TEXTURE_SIZE: ${SCREEN_TEXTURE_SIZE:-1024}
    ports:
      - "1337:1337"
    networks:
      frontend:
        ipv4_address: 10.0.10.1

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.1/16

volumes:
  caddy_data:
  caddy_config:

